name: Build and Deploy Portfolio

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      
      - name: Install dependencies
        run: npm ci --legacy-peer-deps
      
      - name: Build project
        run: npm run build -- --base-href=/Portf-lio-Heitor/
      
      - name: Deploy
        run: |
          cd dist/heitor-dev-portfolio/browser
          git init
          git config user.email "action@github.com"
          git config user.name "GitHub Action"
          git add -A
          git commit -m "Deploy from GitHub Actions"
          git branch -M gh-pages
          git remote add origin "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git"
          git push -u origin gh-pages --force
